
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lssstowqibhdqndagzga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzc3N0b3dxaWJoZHFuZGFnemdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MDc5MTQsImV4cCI6MjA1ODM4MzkxNH0.Dpjs_C0SYuDISktTGFR76XUPe2KT5FXxeJY5LPH13Ug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});
